# Netlify Configuration File
[build]
  # Build command
  command = "npm run build"
  
  # Publish directory (build output)
  publish = "dist"
  
  # Base directory
  base = "/"

# Redirect rules for SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables (configure in Netlify dashboard)
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
